name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          make CXXFLAGS="-DOLD_ACTIVATION_METHOD -DEXPERIMENTAL_FOCUS_FIRST"
      - uses: actions/upload-artifact@v3
        with:
          name: AutoRaise
          path: |
            AutoRaise
            AutoRaise.app
